services:
  psql-dev-db:
    image: postgres:17.4-alpine3.21
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
